#micronaut:
#  application:
#    name: com.micronautCrud
#
#datasources:
#  default:
#    url: jdbc:sqlserver://localhost:1433;databaseName=MicroCrud
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    username: Anemoi
#    password: Anemoi@123
#
#jpa:
#  default:
#    entity-scan:
#      packages: com.micronautCrud
#
#hibernate:
#  hbm2ddl.auto: update
#  show_sql: true
#  dialect: org.hibernate.dialect.SQLServer2019Dialect
micronaut:
  application:
    name: micronautDataJPA
datasources:
  default:
    url: jdbc:sqlserver://localhost:1433;databaseName=MicroCrud
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: Anemoi
    password: Anemoi@123
jpa.default.properties.hibernate.hbm2ddl.auto: none

jpa:
  default:  
    properties:
      hibernate:
        hbm2ddl:
          auto:none
        show_sql: true
